name: appimage-build
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4  # Updated to v4 for Node20 support
    - uses: conda-incubator/setup-miniconda@v3  # Updated to v3 for Node20 support
      with:
        miniconda-version: "latest"
        channels: conda-forge,defaults
        auto-update-conda: true
        python-version: 3.9
        activate-environment: test
    - name: Install CadQuery, CQ-editor, and pyinstaller
      shell: powershell
      run: |
        conda install -c cadquery -c conda-forge cq-editor=master cadquery=master ipython=8.4.0 jedi=0.17.2 pyqtgraph=0.12.4 python=3.9
        pip install --upgrade pyinstaller==5.13.0  # Updated PyInstaller version
        pip install pipwin
        pipwin install numpy
        pip install path
        pip install git+https://github.com/gumyr/cq_warehouse.git#egg=cq_warehouse
        pip install git+https://github.com/meadiode/cq_gears.git@main
        pip install -e "git+https://github.com/CadQuery/cadquery-plugins.git#egg=cq_cache&subdirectory=plugins/cq_cache"
    - name: Run build
      shell: powershell
      run: |
        conda info
        pyinstaller pyinstaller.spec ${{ github.event.inputs.type }}

        # Dynamically locate OpenSSL DLLs and copy them
        $opensslPath = Get-Command openssl | Select-Object -ExpandProperty Source
        $opensslDir = Split-Path -Parent $opensslPath

        if (Test-Path "$opensslDir\libssl-1_1-x64.dll") {
            Copy-Item "$opensslDir\libssl-1_1-x64.dll" "D:\a\CQ-editor\CQ-editor\dist\CQ-editor\" -Force
        } else {
            Write-Host "libssl-1_1-x64.dll not found"
        }

        if (Test-Path "$opensslDir\libcrypto-1_1-x64.dll") {
            Copy-Item "$opensslDir\libcrypto-1_1-x64.dll" "D:\a\CQ-editor\CQ-editor\dist\CQ-editor\" -Force
        } else {
            Write-Host "libcrypto-1_1-x64.dll not found"
        }

        # Check if the source file exists before copying
        if (Test-Path "D:\a\CQ-editor\CQ-editor\pyinstaller\CQ-editor.cmd") {
            Copy-Item "D:\a\CQ-editor\CQ-editor\pyinstaller\CQ-editor.cmd" "D:\a\CQ-editor\CQ-editor\dist\" -Force
        } else {
            Write-Host "CQ-editor.cmd not found"
        }
    - uses: actions/upload-artifact@v4  # Updated to v4 for Node20 support
      with:
        name: CQ-editor-Windows
        path: dist
